[build]
  command = "npm run build"
  publish = "dist"
  environment.NODE_OPTIONS = "--max-old-space-size=4096"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200